### ISSUE TITLE
Documentation or Example Project Request

### ISSUE THREAD

**Issue by parasetam0l** [PaLabs/DatagridBundle#1]
Hello,
I just want to ask is there any documentation or example project to see how this project works.

Thank you. Have a great day!

**Comment by lewbor** [comment]
Hello,
There is a demo app with several examples of usage. I'll try to publish it on github as soon as possible. Thank you for you interest.

**Comment by parasetam0l** [comment]
Hello,
I will wait for it. Thank you for your answer.

**Comment by lewbor** [comment]
https://github.com/PaLabs/demo-app - demo application (DataGrid and Endpoint bundles)

**Comment by parasetam0l** [comment]
Thank you!
